AWSTemplateFormatVersion: '2010-09-09'
Description: 'Book Library Application - Serverless deployment with Lambda, API Gateway, DynamoDB, and S3'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  SecretKey:
    Type: String
    NoEcho: true
    Description: Flask secret key for session management
    MinLength: 32
  
  GoogleBooksAPIKey:
    Type: String
    NoEcho: true
    Default: ''
    Description: Optional Google Books API key for enhanced metadata

Resources:
  # ==================== DynamoDB Tables ====================
  
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'BookLibrary-Users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: username-index
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'BookLibrary-Books-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: book_id
          AttributeType: S
        - AttributeName: isbn
          AttributeType: S
      KeySchema:
        - AttributeName: book_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: isbn-index
          KeySchema:
            - AttributeName: isbn
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  UserBooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'BookLibrary-UserBooks-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_book_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: book_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_book_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: user-book-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: book_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  # ==================== SQS Queue for Async Tasks ====================
  
  MetadataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'BookLibrary-Metadata-${Environment}'
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600  # 14 days
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetadataDeadLetterQueue.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  MetadataDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'BookLibrary-Metadata-DLQ-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  # ==================== S3 Bucket for Static Website ====================
  
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${StaticWebsiteBucket.Arn}/*'

  # ==================== IAM Roles ====================
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'BookLibrary-Lambda-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !GetAtt BooksTable.Arn
                  - !GetAtt UserBooksTable.Arn
                  - !Sub '${UsersTable.Arn}/index/*'
                  - !Sub '${BooksTable.Arn}/index/*'
                  - !Sub '${UserBooksTable.Arn}/index/*'
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:SendMessage'
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource:
                  - !GetAtt MetadataQueue.Arn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  # ==================== Lambda Functions ====================
  
  ApiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'BookLibrary-API-${Environment}'
      Runtime: python3.11
      Handler: lambda_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Placeholder - Deploy actual code'
              }
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          SECRET_KEY: !Ref SecretKey
          USERS_TABLE: !Ref UsersTable
          BOOKS_TABLE: !Ref BooksTable
          USER_BOOKS_TABLE: !Ref UserBooksTable
          METADATA_QUEUE_URL: !Ref MetadataQueue
          GOOGLE_BOOKS_API_KEY: !Ref GoogleBooksAPIKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  MetadataWorkerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'BookLibrary-MetadataWorker-${Environment}'
      Runtime: python3.11
      Handler: tasks_lambda.process_metadata_fetch
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def process_metadata_fetch(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Placeholder - Deploy actual code'
              }
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          USERS_TABLE: !Ref UsersTable
          BOOKS_TABLE: !Ref BooksTable
          USER_BOOKS_TABLE: !Ref UserBooksTable
          GOOGLE_BOOKS_API_KEY: !Ref GoogleBooksAPIKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BookLibrary

  # SQS Event Source Mapping for Metadata Worker
  MetadataWorkerEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MetadataQueue.Arn
      FunctionName: !Ref MetadataWorkerFunction
      BatchSize: 10
      Enabled: true

  # Lambda Permission for API Gateway
  ApiLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiLambdaFunction
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  # ==================== API Gateway ====================
  
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'BookLibrary-API-${Environment}'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - '*'
        MaxAge: 300
      Tags:
        Environment: !Ref Environment
        Application: BookLibrary

  ApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiLambdaFunction.Arn}/invocations'
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 30000

  ApiGatewayRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: '$default'
      Target: !Sub 'integrations/${ApiGatewayIntegration}'

  ApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: '$default'
      AutoDeploy: true
      Tags:
        Environment: !Ref Environment
        Application: BookLibrary

  # ==================== CloudWatch Log Groups ====================
  # Note: Lambda automatically creates log groups, so we don't need to create them explicitly
  # This avoids permission issues with logs:CreateLogGroup

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt ApiGateway.ApiEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  StaticWebsiteURL:
    Description: S3 static website URL
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-StaticWebsiteURL'

  UsersTableName:
    Description: DynamoDB Users table name
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${AWS::StackName}-UsersTable'

  BooksTableName:
    Description: DynamoDB Books table name
    Value: !Ref BooksTable
    Export:
      Name: !Sub '${AWS::StackName}-BooksTable'

  UserBooksTableName:
    Description: DynamoDB UserBooks table name
    Value: !Ref UserBooksTable
    Export:
      Name: !Sub '${AWS::StackName}-UserBooksTable'

  MetadataQueueURL:
    Description: SQS Queue URL for metadata processing
    Value: !Ref MetadataQueue
    Export:
      Name: !Sub '${AWS::StackName}-MetadataQueueURL'
